name: med_reports
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  layrz_theme: ^7.5.7
  layrz_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true